version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build phase..."
  
  build:
    commands:
      - echo "Copying files to build directory..."
      - mkdir -p build
      - cp index.html build/
      
  post_build:
    commands:
      - echo "Preparing artifacts for CodeDeploy..."

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/**/*
  base-directory: '.'
  discard-paths: no
